NUMBER_OF_IDEA: 100 
RELATED_PAPER_NUMBER: 10
RELATED_HIGH_QUALITY_PAPER_NUMBER: 3
SEED_IDEA_INSPIRED_BY_LLM_INTERNAL_KNOWLEDGE: true
SEED_IDEA_INSPIRED_BY_POPULAR_WORK: true
SEED_IDEA_GUIDED_BY_THEORY_OF_SCIENTIFIC_INNOVATION: true
USE_SELF_REFINE: true
STEP0_SAMPLE_NUMBER: 15
STEP1_SAMPLE_NUMBER: 45
STEP2_SAMPLE_NUMBER: 135
OUTPUT_DIR: "output"

ACADEMIC_SEARCH_ENGINE_IP_ADDRESS: "http://0.0.0.0:9918/"
MAX_RETRY_TIMES_FOR_ACADEMIC_SEARCH_ENGINE: 6
EMBEDDING_URL: "http://0.0.0.0:9918/compute_embedding"
EMBEDDING_MODEL_DIR: "all-MiniLM-L6-v2"
RERANK_MODEL_DIR: "ms-marco-MiniLM-L-6-v2"
FAISS_INDEX_DIR: "faiss/"

LLM_COMPANY: "openai"
# LLM_COMPANY: "deepseek"
# LLM_COMPANY: "anthropic"
# OPENAI LLM MODEL
use_native_openai: false
NATIVE_OPENAI_MODEL_NAME: "gpt-4o"
OPENAI_API_KEY: ""
OPENAI_BASE_URL: ""
AZURE_OPENAI_MODEL_NAME: "gpt-4o"
# set it if you set is_azure to True
AZURE_OPENAI_ENDPOINT : ""
AZURE_OPENAI_KEY : ""
AZURE_OPENAI_API_VERSION : ""
# DEEPSEEK LLM MODEL
DEEPSEEK_API_KEY: ""
